# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c03e2819d898eaf6426c31039c957e4decc456f4d77215663a2074b71210c11c7a2ab3a3831563b7a687e75c8c345a5fac50f11b6403f41f4a5b4dcf56756fde

test:
  secret_key_base: fd600edd41f93ec577973d9099b97005c1babbb5fb75afc0b7aed4c7814cb1650d115315fbe6c944dc1085bf0aabea4a27917d371c516ec99f788a1fd38fd8ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
